org: luchorene97
app: aws-lamba-crud-node
service: aws-lamba-crud-node
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements: 
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:246683218639:table/Tasks

functions:
  hello:
    handler: src/index.hello
    events:
      - httpApi:
          path: /
          method: get
  createTask:
    handler: src/tasks/createTask.createTask
    events:
      - httpApi:
          path: /tasks
          method: post
  getTasks:
    handler: src/tasks/getTasks.getTasks
    events:
      - httpApi:
          path: /tasks
          method: get
  getTask:
    handler: src/tasks/getTask.getTask
    events:
      - httpApi:
          path: /tasks/{id}
          method: get
  updateTask:
    handler: src/tasks/updateTask.updateTask
    events:
      - httpApi:
          path: /tasks/{id}
          method: put
  deleteTask:
    handler: src/tasks/deleteTask.deleteTask
    events:
      - httpApi:
          path: /tasks/{id}
          method: delete

resources: 
  Resources:
    TasksTable: 
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: Tasks
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
        - AttributeName: id
          KeyType: HASH
